# Generated by Django 5.2.6 on 2026-01-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitortracking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='visitortracking',
            name='browser_language',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visitortracking',
            name='client_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitortracking',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='visitortracking',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='visitortracking',
            name='screen_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitortracking',
            name='session_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='visitortracking',
            name='shared_by_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitortracking',
            name='shared_from_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitortracking',
            name='shared_from_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitortracking',
            name='shared_via',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitortracking',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitortracking',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitortracking',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitortracking',
            name='utm_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitortracking',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visitortracking',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitortracking',
            name='content_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='visitortracking',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitortracking',
            name='referrer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitortracking',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitortracking',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='visitortracking',
            index=models.Index(fields=['session_id', 'created_at'], name='user_visito_session_3334fb_idx'),
        ),
        migrations.AddIndex(
            model_name='visitortracking',
            index=models.Index(fields=['content_id', 'created_at'], name='user_visito_content_1cbfee_idx'),
        ),
        migrations.AddIndex(
            model_name='visitortracking',
            index=models.Index(fields=['ip_address', 'created_at'], name='user_visito_ip_addr_95eaf7_idx'),
        ),
    ]
