# Generated by Django 5.2.6 on 2026-01-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_visitortracking_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitortracking',
            name='fingerprint',
            field=models.CharField(db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='visitortracking',
            name='session_id',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
