# Generated by Django 5.2.6 on 2025-09-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CREATOR', 'Creator'), ('MANAGER', 'Manager'), ('SUPPORT', 'Support'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=20),
        ),
    ]
